#
# Module manifest for module 'HammerspaceModule'
#
# Generated by Simtheory for John Olson
#

@{

# A unique identifier for this module. 
GUID = '36c4d3cd-62b2-4822-851a-e8f847fd26d2'

# The author of this module
Author = 'John Olson'

# Company or vendor of this module
CompanyName = 'Hammerspace'

# Copyright statement for this module
Copyright = '(c) 2025 John Olson. All rights reserved.'

# Description of the functionality of this module
Description = 'A PowerShell module for interacting with the Hammerspace API.'

# Version number of this module.
ModuleVersion = '1.0.0'

# Minimum version of PowerShell required by this module. We set this to 5.1 due to our compatibility fixes.
PowerShellVersion = '5.1'

# Name of the PSSnapIn on which this module depends
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module. We need System.Web for URL encoding.
RequiredAssemblies = @('System.Web')

# Script files (.ps1) that are executed in the caller's scope when the module is imported.
# FilesToProcess = @()

# --- CORE MODULE STRUCTURE ---


RootModule = ''

NestedModules = @(
    # Private helper functions
    'Private/Connection.ps1',
    'Private/Helpers.ps1',
    'Private/Internal.ps1',

    # Public, user-facing functions
    'Public/Connect-Hammerspace.ps1',
    'Public/Get-HammerspaceRaw.ps1',
    'Public/Get-HammerspaceShare.ps1',
    'Public/Get-HammerspaceTask.ps1',
    'Public/New-HammerspaceExportOption.ps1',
    'Public/New-HammerspaceRaw.ps1',
    'Public/New-HammerspaceShare.ps1',
    'Public/New-HammerspaceShareObjective.ps1',
    'Public/New-HammerspaceExportOption.ps1',
    'Public/Remove-HammerspaceShare.ps1',
    'Public/HammerspaceSnmp.ps1',
    'Public/Remove-HammerspaceRaw.ps1'
)

# --- EXPORTING COMMANDS ---

# Functions to export from this module. These are the commands the user can run.
FunctionsToExport = @(
    # Connection and Login
    'Initialize-HammerspaceConnection',
    'Invoke-HammerspaceLogin',

    # Public Functions
    'Connect-Hammerspace',
    'Get-HammerspaceShare',
    'New-HammerspaceShare',
    'New-HammerspaceShareObjective',
    'New-HammerspaceExportOption',
    'Remove-HammerspaceShare',
    'Get-HammerspaceTask',
    'Get-HammerspaceSnmpConfiguration',
    'New-HammerspaceSnmpConfiguration',
    'Set-HammerspaceSnmpConfiguration',
    'Remove-HammerspaceSnmpConfiguration',
    'Test-HammerspaceSnmpNotification',

    
    # Raw functions (kept public as per our usage)
    'Get-HammerspaceRaw',
    'New-HammerspaceRaw',
    'Remove-HammerspaceRaw'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = @()

# Private data to pass to the module. Can be used for configuration.
PrivateData = @{
    PSData = @{
        # Tags for the PowerShell Gallery
        Tags = @('Hammerspace', 'Storage', 'API')
    }
}

}